---
- hosts: localhost
  become: yes
  tasks: 
  - name: create ansible ubuntu nodes
    ec2:
      key_name: mysmartkey
      instance_type: t2.micro
      image: ami-05014693df353053e
      wait: yes
      group: NONE
      region: us-east-2
      count: 2
      vpc_subnet_id: subnet-b37fc6d8
      assign_public_ip: yes
      instance_tags:
        Name: myAnsibleUbuntuNode
